
import './globals.css'

import { Locale, i18n } from '@/i18n.config'

import HeaderComponent from './components/headerComponent';

type Metadata = {
  title: string;
  description: string;
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  return (
    <html lang={params.lang}>
      <body >
      
        <HeaderComponent lang={params.lang} />
        <main>{children}</main>
      </body>
    </html>
  )
}
